config/routes.rb
Rails.application.routes.draw do

  # mostly-static pages
  root 'static_pages#welcome'
  get '/support', to: 'static_pages#support'
  get '/about', to: 'static_pages#about'
  get '/started', to: 'static_pages#getting_started'

  # User model, custom routes above resources to match first
  get '/signup', to: 'users#new'
  get '/history/:id', to: 'users#history', as: 'history'
  post '/signup', to: 'users#create'
  resources :users, only: [:show, :edit, :index, :update, :destroy]

  # user account login system
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # markers
  get '/start', to: 'markers#start'
  post '/curriculum', to: 'markers#begin_curriculum'
  get '/theories', to: 'markers#theories'
  get '/resume', to: 'markers#resume_curriculum'
  post '/category/next', to: 'markers#next_category'
  post '/category/skip', to: 'markers#skip_category'
  delete '/start', to: 'markers#reset_curriculum'
  post '/problem/skip', to: 'markers#skip_problem'
  get '/next', to: 'markers#next_unlocked_by_context'

  # answers
  get '/solve/:id', to: 'answers#problem', as: 'solve'
  post '/solve/evaluate', to: 'answers#evaluate'
  post '/solve/:id', to: 'answers#get_hint', as: 'get_hint'

  # problems
  resources :problems, except: [:new, :create]

  # theories
  get '/view/:id', to: 'theories#view', as: 'view'
  get '/theories/index', to: 'theories#index'
  resources :theories, except: [:new, :create, :index]

  # globalgraphs
  resources :globalgraphs, only: [:index, :show]

  # graphs
  resources :graphs, only: [:index, :show]

  # curriculum pages for teachers/admins
  get '/curriculum/edit', to: 'curriculum#index'
  get '/curricula', to: 'curriculum#curricula'
  get '/curriculum/categories', to: 'curriculum#categories'
  get '/curriculum/contexts', to: 'curriculum#contexts'
  get '/curriculum/files', to: 'curriculum#files'
  get '/curriculum/history', to: 'curriculum#history'

end

app/models/marker.rb
class Marker < ApplicationRecord
  belongs_to :user
  # NOTE curriculum = book, catgegory = chapter, context = section
  # The Marker model has as much code as possible for the part responsible
  # for keeping track of a student's progression through the curriculum.
  #
  # one marker for each book for each student
  #
  # marker knows which single chapter the student is currently in, for that book
  #
  # marker asks Globalgraph questions about sections and asks Graph questions
  # about files in those sections
  #
  # modus operandi is to continously unlock theory files until a problem
  # is reached; this is true within each section

  # call globalgraph and graph to unlock beginning theories and problems
  def begin_curriculum(curriculum)
    # set category
    category = Globalgraph.get_beginning_category(curriculum)
    update_attribute(:category, category)
    begin_category(curriculum, category)
  end

  def next_category(curriculum, category)
    # category will be nil if no category remains
    category = Globalgraph.get_next_category(curriculum, category)
    # 'finished' is the flag to indicate a complete book
    unless category
      category = 'finished'
    end
    begin_category(curriculum, category)
  end

  def begin_category(curriculum, category)
    update_attribute(:category, category)
    unless category == 'finished'
      # unlock category introductions
      theories = Globalgraph.get_beginning_theories(curriculum, category)
      theories.each do |theory|
        set_unlocked_theory(theory)
      end

      # unlock first problem, and every theory prior, in each context of
      # beginning category
      contexts = Globalgraph.get_beginning_contexts(curriculum, category)
      contexts.each do |context|
        # call graph for beginning file of context
        file = Graph.get_first_file(category, context)
        # keep pulling files until a problem is found or end of context
        set_until_problem(file)
      end
    end
  end

  def set_next_problem(problem_id)
    file = Graph.get_next('prob', problem_id)
    set_until_problem(file)
  end

  private

  # takes a file of format {typ: typ, id: id}, which represents a file in
  # a context; sets that file and all following theory files, in that context,
  # until the next problem in that context is found and set
  def set_until_problem(file)
    continue = true
    while continue
      # if end of context or unknown error
      if file[:typ] == nil
        continue = false
      # elsif theory file, unlock and continue
      elsif file[:typ] == 'theory'
        set_file(file)
      # elsif regular problem file, unlock but do not continue
      elsif !file[:makeup]
        set_file(file)
        continue = false
      # elsif makeup file
      elsif file[:makeup]
        # check if makeup wanted
        makeup = Score.problem_set(user.id, file[:id], file[:batch])
        if makeup
          # unlock makeup and do not skip
          set_file(file)
          continue = false
        else
          # give makeup a score of 0 and continue
          skip_problem(file[:id])
        end
      else
        raise "unknown return from Graph calls during set_until_problem"
      end
      # if while loop continued, get next file
      if continue
        file = Graph.get_next(file[:typ], file[:id])
      end
    end
  end

  # takes a file of format {typ: typ, id: id} and unlocks it for the user
  def set_file(file)
      if file[:typ] == nil
        raise "cannot set a file returned as end of context flag"
      elsif file[:typ] == 'theory'
        set_unlocked_theory(file[:id])
      elsif file[:typ] == 'prob'
        set_new_problem(file[:id])
      else
        raise "unknown return from Graph during set_file"
      end
  end

    # TODO replace DB get with passing parameters, refactor & test
    def set_unlocked_theory(id)
      theory = Theory.find(id)
      user.unlocked_theories.create!(theory_id: id,
                                     curriculum: theory.curriculum,
                                     category: theory.category,
                                     context: theory.context,
                                     seen: false)
    end

    # TODO replace DB get with passing parameters, refactor & test
    def set_new_problem(id)
      prob = Problem.find(id)
      batchNum = Graph.find_by(file_id: id, typ: 'prob').batch
      user.scores.create!(problem_id: id, ip: true,
                          curriculum: prob.curriculum,
                          category: prob.category,
                          context: prob.context,
                          batch: batchNum)
    end

    # skips file with a score of 0, good for skipping makeups
    def skip_problem(id)
      # prevent skipping a problem that has already been taken
      prob = Problem.find(id)
      batchNum = Graph.find_by(file_id: id, typ: 'prob').batch
      user.scores.create!(problem_id: id, ip: false,
                          curriculum: prob.curriculum,
                          category: prob.category,
                          context: prob.context,
                          score: 0,
                          batch: batchNum)

    end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :least_teacher, only: [:skip_category, :reset_curriculum]
  before_action :least_user
  before_action :open_book, only: :resume_curriculum
  before_action :finished_category, only: :next_category

  def index
  end

  def begin_curriculum
    # TODO strong params
    marker = current_user.markers.create!(curriculum: params[:curriculum])
    marker.begin_curriculum(params[:curriculum])
    redirect_to resume_path(curriculum: params[:curriculum])
    # if already purchased, tell user to reset if desired otherwise resume
    # elsif "saved" (all unlocks done) notify user of success and proceed
    # else error (user not logged in? etc)
  end

  def next_category
    curriculum = params[:curriculum]
    marker = current_user.markers.find_by(curriculum: curriculum)
    marker.next_category(curriculum, marker.category)
    redirect_to resume_path(curriculum: curriculum)
  end

  # TODO remove lifetomath hard code, need to enhance tool in view
  def skip_category
    marker = current_user.markers.find_by(curriculum: 'lifetomath')
    if marker
      # next category code
      marker.next_category('lifetomath', marker.category)
      redirect_to resume_path(curriculum: 'lifetomath')
    else
      # begin curriculum code and next category code in sequence
      marker = current_user.markers.create!(curriculum: 'lifetomath')
      marker.begin_curriculum('lifetomath')
      marker.next_category('lifetomath', marker.category)
      redirect_to resume_path(curriculum: 'lifetomath')
    end
  end

  # redirects user to next unlocked file in context (theory or problem)
  def next_unlocked_by_context
    # get next unlocked & unseen theory, if nil get next problem
    # TODO sort by oldest unseen unlocked theory
    next_theory = UnlockedTheory.find_by(user_id: current_user.id,
                                         context: params[:context],
                                         seen: false)
    if next_theory
      redirect_to view_path(id: next_theory.theory_id)
    else
      next_problem = Score.find_by(user_id: current_user.id,
                              context: params[:context],
                              ip: true)
      if next_problem
        redirect_to solve_path(id: next_problem.problem_id)
      else
        flash[:info] = "You have finished that section."
        redirect_to resume_path(curriculum: 'lifetomath')
      end
    end
  end

  # TODO lots of code change and no testing, not in website atm anyway
  # TODO make this teacher+ priv, fix all lack of security/permissions/checks
  # def skip_problem
    # prob = Problem.find(params[:id])
    # # TODO replace hardcoded lifetomath with curriculum after script update
    # marker = current_user.markers.find_by(curriculum: 'lifetomath')
    # # TODO actual score method, something along the lines of answer_problem
    # score = Score.find_by(user_id: current_user.id, problem_id: prob.id)
    # score.update_attribute(:ip, false)
    # marker.set_next_problem(prob.id)
    # # redirect_to newest score
    # redirect_to action: "next_unsolved_problem_by_context", context: prob.context
  # end

  # TODO make this curriculum-specific, requires enhancing tool in view
  def reset_curriculum
    UnlockedTheory.where(user_id: current_user.id).destroy_all
    Score.where(user_id: current_user.id).destroy_all
    Marker.where(user_id: current_user.id).destroy_all
    SeenHint.where(user_id: current_user.id).destroy_all
    redirect_to start_path
  end

  # TODO optimize, use actual comp sci after better design
  def resume_curriculum
    curriculum = params[:curriculum]
    marker = current_user.markers.find_by(curriculum: curriculum)

    # get all active contexts (unread theories or unsolved problems) in cat
    unsolved = Score.where(user_id: current_user.id,
                         category: marker.category,
                         ip: true)
    unread = UnlockedTheory.where(user_id: current_user.id,
                                            category: marker.category,
                                            seen: false)
    # create a list of all active contexts for category
    unorderedContexts = []
    unsolved.each do |score|
      unless unorderedContexts.include? score.context
        unorderedContexts << score.context
      end
    end
    unread.each do |unlock|
      unless unorderedContexts.include? unlock.context
        unorderedContexts << unlock.context
      end
    end

    # create list of sections, both active and inactive
    categoryOrdering = Globalgraph.where(category: marker.category)
    @activeContexts = []
    @finishedContexts = []
    @status = []
    categoryOrdering.each do |tuple|
      if unorderedContexts.include? tuple.context
        @activeContexts << tuple.context
        @status << true
      else
        @finishedContexts << tuple.context
        @status << false
      end
    end

    # for when active contexts is empty
    @category = marker.category
    # for page heading
    @curriculum = curriculum

    render '/markers/resume'
  end

  def theories
    @unlocked_theories = current_user.unlocked_theories.all
    @categories = []
    # create a list of every category
    @unlocked_theories.each do |unlocked|
      if unlocked.category != @categories.last
        @categories << unlocked.category
      end
    end

    # {category => [context1, context2, ect]}
    @directories = {}
    @categories.each do |category|
      # for a category, get all tuples
      in_category = @unlocked_theories.where(category: category)
      contexts = []
      in_category.each do |tuple|
        if tuple.context != contexts.last
          contexts << tuple.context
        end
      end
      @directories[category] = contexts
    end
  end

  private

    def open_book
      marker = current_user.markers.find_by(curriculum: params[:curriculum])
      # if user doesn't have a marker for that book
      unless marker
        flash[:danger] = "You do not have that book open."
        redirect_to start_path and return
      end
      # if user has finished that book
      if marker.category == 'finished'
        flash[:success] = "Congratulations, you have completed" \
          " the #{$PPB[params[:curriculum]]} book!"
        redirect_to start_path
      end
    end

    def finished_category
      marker = current_user.markers.find_by(curriculum: params[:curriculum])
      unless marker
        flash[:danger] = "You do not have that book open."
        redirect_to start_path and return
      end
      # ip_category is nil if no open problems found in category
      if Score.ip_category(current_user.id, marker.category)
        flash[:danger] = "You have not completed your current chapter."
        redirect_to resume_path(curriculum: params[:curriculum])
      end
    end
end

app/views/markers/index.html.erb
<%provide(:title, 'Curriculum')%>
<h1>Life to Math</h1>
<% if current_user.markers.find_by(curriculum: 'lifetomath') %>
  <p><%= link_to 'Resume Here', resume_path(curriculum: 'lifetomath') %></p>
<% else %>
  <p><%= link_to 'Start Here', curriculum_path(curriculum: 'lifetomath'), method:
  :post  %></p>
<% end %>
<h1>Let's Count</h1>
<%= link_to 'Start Here (incomplete)', '#' %>
<% if is_teacher %>
  <h2>Teacher Tools</h2>
  <p><%= link_to 'Delete All of Your Progress', start_path, method: :delete %></p>
<% end %>

app/views/markers/resume.html.erb
<div class="container">
 <ul class="nav nav-pills">
   <li><a href="/start"><b><%= $PPB[@curriculum] %></b></a></li>
   <li class="active"><a href=<%="/resume?curriculum=#{@curriculum}"%>>
       <%= $PPC[@category] %> <b>&nbsp ></b></a></li>
</ul>
</div>
<div class="container">
<h2 style="text-align:center;"><%= $PPB[@curriculum]%></h2>
<% if @activeContexts.empty? %>
  <div class="well">
    <h4><%= "Congratulations, you've completed the #{$PPC[@category]} chapter." %></h4>
    <%= link_to 'Next Chapter', category_next_path(curriculum: @curriculum), method: :post%>
  </div>
  <hr>
<% end %>
</div>
<%# get all chapters in the book %>
<% chapters = Globalgraph.category_names(@curriculum) %>
<%# counters related to chapters drawn and total chapters %>
<% chpMax = chapters.length %>
<% chpsPrinted = 0 %>
<%# count for chapters per row %>
<% perRow = 2 %>
<% chpCount = perRow %>
<div class="container">
  <%# for every chapter in the book print a list of sections %>
  <% chapters.each do |chapter| %>
    <% chpsPrinted += 1 %>
    <% chpCount += 1 %>
    <%# determine if a new row should be constructed; every 2? 3? %>
    <% if chpCount > perRow %>
      <%# reset counter %>
      <% chpCount = 1 %>
      <%# create row %>
      <div class="row">
    <% end %>
    <%# print chapter title to serve as list header %>
    <div class="col-sm-4 col-sm-offset-2">
      <h4><%= $PPC[chapter] %></h4>
    <ol>
      <%# if it is an active chapter %>
      <% if chapter == @category %>
        <% @status.each do |status| %>
          <% context = nil %>
          <% if status %>
            <% context = @activeContexts.shift %>
            <li><%= link_to $PPS[context], next_path(context: context) %></li>
          <% else %>
            <% context = @finishedContexts.shift %>
            <li><%= $PPS[context] %></li>
          <% end %>
        <% end %>
      <%# else it is an inactive chapter %>
      <% else %>
        <%# for each section in this chapter print a li %>
        <% sections = Globalgraph.context_names(chapter) %>
        <% sections.each do |section| %>
          <li><%= $PPS[section] %></li>
        <% end %>
      <% end %>
    </ol>
  </div>
  <%# end row after 2 chapters printed or last chapter printed %>
  <% if chpsPrinted == chpMax %>
    </div>
  <% elsif chpCount == perRow %>
    </div>
    <hr>
  <% end %>
<% end %>
</div>
<%# while chapters remain in book print remaining inactive sections %>
<% if is_teacher %>
<div class="container">
<hr>
<h3>(Teacher Tools)</h3>
<ul>
  <li><%= link_to 'Skip Current Category and Resume', category_skip_path, method: :post %></li>
  <li><%= link_to 'Delete All of Your Progress', start_path, method: :delete %></li>
</ul>
</div>
<% end %>

app/views/markers/start.html.erb
<%provide(:title, 'Books')%>
<div class="container">
  <h2>Life to Math</h2>
  <% if current_user.markers.find_by(curriculum: 'lifetomath') %>
    <p><%= link_to 'Resume Here', resume_path(curriculum: 'lifetomath') %></p>
  <% else %>
    <p><%= link_to 'Start Here', curriculum_path(curriculum: 'lifetomath'), method:
      :post  %></p>
  <% end %>
  <h2>Let's Count</h2>
  <%= link_to '(Dead Link Until Globalgraph and Graphs Are Made)', '#' %>
  <% if is_teacher %>
    <hr>
    <h3>(Teacher Tools)</h3>
    <ul>
      <li><%= link_to 'Skip Current Category and Resume', category_skip_path, method: :post %></li>
      <li><%= link_to 'Delete All of Your Progress', start_path, method: :delete %></li>
      <ul>
      <% end %>
</div>

app/views/markers/theories.html.erb
  <div class="row">
    <%# main content here %>
    <div class="col-sm-12 col-md-8 col-md-offset-2">
      <% @directories.each do |category, context_list| %>
        <div class="row theory-index-category-row">
          <h2 class="text-center"><%= $PPC[category] %></h2>
          <% context_list.each do |context| %>
            <div class="col-sm-12 col-md-6 col-lg-4">
              <h4><%= $PPS[context] %></h4>
              <ol>
                <% unlocks = @unlocked_theories.where(category: category, context: context) %>
                <% unlocks.each do |unlock| %>
                  <% theory = Theory.find(unlock.theory_id) %>
                  <li><%= link_to theory.filename, view_path(theory.id) %></li>
                <% end %>
              </ol>
            </div>
          <% end %>
        </div>
        <hr>
      <% end %>
    </div>
  </div>