config/routes.rb
Rails.application.routes.draw do

  # mostly-static pages
  root 'static_pages#welcome'
  get '/support', to: 'static_pages#support'
  get '/about', to: 'static_pages#about'
  get '/started', to: 'static_pages#getting_started'

  # User model, custom routes above resources to match first
  get '/signup', to: 'users#new'
  get '/history/:id', to: 'users#history', as: 'history'
  post '/signup', to: 'users#create'
  resources :users, only: [:show, :edit, :index, :update, :destroy]

  # user account login system
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # markers
  get '/start', to: 'markers#start'
  post '/curriculum', to: 'markers#begin_curriculum'
  get '/theories', to: 'markers#theories'
  get '/resume', to: 'markers#resume_curriculum'
  post '/category/next', to: 'markers#next_category'
  post '/category/skip', to: 'markers#skip_category'
  delete '/start', to: 'markers#reset_curriculum'
  post '/problem/skip', to: 'markers#skip_problem'
  get '/next', to: 'markers#next_unlocked_by_context'

  # answers
  get '/solve/:id', to: 'answers#problem', as: 'solve'
  post '/solve/evaluate', to: 'answers#evaluate'
  post '/solve/:id', to: 'answers#get_hint', as: 'get_hint'

  # problems
  resources :problems, except: [:new, :create]

  # theories
  get '/view/:id', to: 'theories#view', as: 'view'
  get '/theories/index', to: 'theories#index'
  resources :theories, except: [:new, :create, :index]

  # globalgraphs
  resources :globalgraphs, only: [:index, :show]

  # graphs
  resources :graphs, only: [:index, :show]

  # curriculum pages for teachers/admins
  get '/curriculum/edit', to: 'curriculum#index'
  get '/curricula', to: 'curriculum#curricula'
  get '/curriculum/categories', to: 'curriculum#categories'
  get '/curriculum/contexts', to: 'curriculum#contexts'
  get '/curriculum/files', to: 'curriculum#files'
  get '/curriculum/history', to: 'curriculum#history'

end

app/models/theory.rb
class Theory < ApplicationRecord
  has_many :unlocked_theories
  validates :filename, :text, :curriculum, :category, :context, presence: true
  validate :text_cannot_begin_lowercase_letter

  default_scope -> { order(filename: :asc)}
end

app/controllers/theories_controller.rb
class TheoriesController < ApplicationController
  before_action :least_teacher, except: :view

  def index
    @theories = Theory.all.paginate(page: params[:page])
  end

  # teacher tool viewer
  def show
    @theory = Theory.find(params[:id])
  end

  # views are outside of teacher tool, part of curriculum progression
  def view
    @theory = Theory.find(params[:id])
    @first_viewing = true
    toMark = @theory.unlocked_theories.find_by(user_id: current_user.id)
    if toMark and toMark.seen
      @first_viewing = false
    elsif toMark
      toMark.update_attribute(:seen, true)
    else
      flash[:danger] = "You do not have access to that theory file."
      redirect_to root_path
    end
  end

  def edit
    @theory = Theory.find(params[:id])
  end
end

app/views/theories/edit.html.erb
<div class="container"><h2><%= "This is the temporary edit page for #{@theory.filename}" %></h2></div>

app/views/theories/index.html.erb
<div class="container">
  <% provide(:title, 'Theories Index') %>
  <h2>All Theories</h2>

  <%= will_paginate %>

  <ul class="theories">
    <% @theories.each do |theory| %>
      <li>
        <%= link_to theory.filename, theory %>
        <% if is_teacher %>
          | <%= link_to "edit", edit_theory_url(theory.id) %>
      <% end %>
      </li>
    <% end %>
  </ul>

  <%= will_paginate %>
</div>

app/views/theories/show.html.erb
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_CHTML">
</script>
<%# TODO pretty name %>
<% provide(:title, "#{@theory.filename}") %>

<div class="container">
  <h4><%= @theory.filename %></h4>

  <%== @theory.text %>
</div>
<%# temporary hack to get mathjax to typeset the page after page loaded %>
<script>
  MathJax.Hub.Typeset();
</script>

app/views/theories/view.html.erb
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_CHTML">
</script>
<% provide(:title, "#{@theory.filename}") %>

<div class="container">
 <ul class="nav nav-pills">
   <li><a href="/start"><b><%= $PPB[@theory.curriculum] %></b></a></li>
   <li><a href=<%="/resume?curriculum=#{@theory.curriculum}"%>>
       <%= $PPC[@theory.category] %> <b>&nbsp ></b></a></li>
   <li class="active"><a href="#"><%= $PPS[@theory.context] %></a></li>
</ul>
</div>
<br>
<div class="container">
  <div class="well well-lg"><%== @theory.text %></div>

  <% if @first_viewing %>
    <em><%= "Since this is the first time you are viewing this theory, you may
  jump to the next part of \"#{$PPS[@theory.context]}\" with this link:" %></em>
    <p><%= link_to $PPS[@theory.context], next_path(context: @theory.context) %></p>
  <% else %>
    <em> <%= link_to "Curriculum", start_path %></em>
  <% end %>
</div>
<%# temporary hack to get mathjax to typeset the page after page loaded %>
<script>
MathJax.Hub.Typeset();
</script>