config/routes.rb
Rails.application.routes.draw do

  # mostly-static pages
  root 'static_pages#welcome'
  get '/support', to: 'static_pages#support'
  get '/about', to: 'static_pages#about'
  get '/started', to: 'static_pages#getting_started'

  # User model, custom routes above resources to match first
  get '/signup', to: 'users#new'
  get '/history/:id', to: 'users#history', as: 'history'
  post '/signup', to: 'users#create'
  resources :users, only: [:show, :edit, :index, :update, :destroy]

  # user account login system
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # markers
  get '/start', to: 'markers#start'
  post '/curriculum', to: 'markers#begin_curriculum'
  get '/theories', to: 'markers#theories'
  get '/resume', to: 'markers#resume_curriculum'
  post '/category/next', to: 'markers#next_category'
  post '/category/skip', to: 'markers#skip_category'
  delete '/start', to: 'markers#reset_curriculum'
  post '/problem/skip', to: 'markers#skip_problem'
  get '/next', to: 'markers#next_unlocked_by_context'

  # answers
  get '/solve/:id', to: 'answers#problem', as: 'solve'
  post '/solve/evaluate', to: 'answers#evaluate'
  post '/solve/:id', to: 'answers#get_hint', as: 'get_hint'

  # problems
  resources :problems, except: [:new, :create]

  # theories
  get '/view/:id', to: 'theories#view', as: 'view'
  get '/theories/index', to: 'theories#index'
  resources :theories, except: [:new, :create, :index]

  # globalgraphs
  resources :globalgraphs, only: [:index, :show]

  # graphs
  resources :graphs, only: [:index, :show]

  # curriculum pages for teachers/admins
  get '/curriculum/edit', to: 'curriculum#index'
  get '/curricula', to: 'curriculum#curricula'
  get '/curriculum/categories', to: 'curriculum#categories'
  get '/curriculum/contexts', to: 'curriculum#contexts'
  get '/curriculum/files', to: 'curriculum#files'
  get '/curriculum/history', to: 'curriculum#history'

end

app/controllers/curriculum_controller.rb
class CurriculumController < ApplicationController
  before_action :least_teacher

  # NOTE the significance of having a curriculum controller is syncing RESTful
  # actions for the globalgraph/graph controllers with RESTful actions of the
  # content controllers like problems (creating a problem and adding it to the
  # curriculum progression)

  # page for analytics
  def history
    # TODO some pagination (can't use .paginate, not an association)
    @all = Score.activity
  end

  # TODO search feature, otherwise it seems pointless (well it has graphs)
  def index
  end

  def curricula
  end

  def categories
    # TODO fix for multiple curricula
    all = Globalgraph.order(category_order: :asc)
    @curriculum = all.first.curriculum
    @cat_list = []
    all.each do |tuple|
      unless @cat_list.include? tuple.category
        @cat_list << tuple.category
      end
    end
  end

  def contexts
    # all tuples from globalgraph for this category
    all = Globalgraph.where(category: params[:category])
    @category = params[:category]
    @cat_intro_ids = []
    @context_list = []
    # process theory files and context directories
    all.each do |item|
      # seperate theoryfile from context directories
      if item.context == 'category_introduction'
        theoryfile = Theory.find_by(category: params[:category], context:
                    'category_introduction')
        @cat_intro_ids << theoryfile.id
      # if new context, add it to list
      else
        unless @context_list.include? item.context
          @context_list << item.context
        end
      end
    end
  end

  # should be an ordered, by graph priorities, list of files in the context
  # with the type of file (theory, problem), the file name, and if it is
  # a makeup denoted cleanly...also maybe group by batch using <br>
  def files
    @graphs = Graph.where(context: params[:context])
  end
end

app/views/curriculum/categories.html.erb
<div class="container">
  <h3><%= "Categories for #{@curriculum}:" %></h3>
  <ol>
    <% @cat_list.each do |category| %>
      <li><%= link_to category, curriculum_contexts_path(category: category) %></li>
    <% end %>
    </ul>
</div>

app/views/curriculum/contexts.html.erb
<div class="container">
  <h3><%= "Introduction to #{@category}" %></h3>
  <ol>
    <% @cat_intro_ids.each do |id| %>
      <li><%= link_to 'Introduction Theory', theory_path(id) %></li>
    <% end %>
  </ol>
  <h3><%= "Contexts of #{@category}:" %></h3>
  <ol>
    <% @context_list.each do |context| %>
      <li><%= link_to context, curriculum_files_path(context: context) %></li>
    <% end %>
  </ol>
</div>

app/views/curriculum/curricula.html.erb
<div class="container">
  <%provide(:title, 'Curriculum')%>
  <h2>Life to Math</h2>
  <%= link_to 'Start Here', curriculum_categories_path %>
  <h2>Let's Count</h2>
  <%= link_to '(Dead Link Until Globalgraph and Graphs Made)', '#' %>
</div>

app/views/curriculum/files.html.erb
<div class="container">
  <h3><%= "#{@graphs.first.context}" %></h3>
  <ol>
    <% set = 0 %>
    <% @graphs.each do |graph| %>
      <%# TODO horizontal line %>
      <% unless set == graph.batch %>
        <% set += 1 %>
        <hr>
      <% end %>
      <li>
        <% if graph.typ  == 'prob' %>
          <% file = Problem.find(graph.file_id) %>
          Problem: <%= link_to file.filename, problem_path(file) %>
      <% elsif graph.typ == 'theory' %>
        <% file = Theory.find(graph.file_id) %>
        Theory: <%= link_to file.filename, theory_path(file) %>
    <% else %>
      <b><%= "Bug detected, file id: #{graph.file_id} of type: #{graph.typ}
    was not found." %></b>
    <% end %>
    <ul>
      <li><%= "Set: #{graph.batch}" %></li>
      <li><%= "Order: #{graph.order}" %></li>
      <% if graph.makeup %>
        <li>Makeup</li>
      <% end %>
    </ul>
      </li>
    <% end %>
  </ol>
</div>

app/views/curriculum/history.html.erb
<div class="container">
  <h3>All Users Activity (temporary placeholder)</h3>
  <em><p>Note: this page will change dramatically to include menus, plots, time
    frames, scopes, and much more data; needs javascript first</p></em>
  <ol>
    <% @all.each do |hash| %>
      <li>
        <ul>
          <li><%= "#{hash[:curriculum]}, #{hash[:category]},
        #{hash[:context]}, #{hash[:filename]}" %> </li>
          <li><%= "user: #{hash[:user]}" %></li>
          <li><%= "score: #{hash[:score]}" %></li>
          <li><%= "hints requested: #{hash[:hints]}" %></li>
          <li><%= "difficulty: #{hash[:difficulty]}" %></li>
          <li><%= "start time: #{hash[:start]}" %></li>
          <li><%= "end time: #{hash[:finish]}" %></li>
        </ul>
      </li>
      <br>
    <% end %>
  </ol>
</div>

app/views/curriculum/index.html.erb
<div class="container">
  <%provide(:title, 'Curriculum')%>
  <h3>Problems</h3>
  <ul><li><%= link_to 'Problems', problems_path %></li></ul>
  <h3>Theories</h3>
  <ul><li><%= link_to 'Theories', theories_index_path %></li></ul>
  <h3>Graphs</h3>
  <ul>
    <li><%= link_to 'Globalgraphs', globalgraphs_path %></li>
    <li><%= link_to 'Graphs', graphs_path %></li>
  </ul>
  <hr>
  <h5>(note: search not yet available for any index)</h5>
</div>