config/routes.rb
Rails.application.routes.draw do

  # mostly-static pages
  root 'static_pages#welcome'
  get '/support', to: 'static_pages#support'
  get '/about', to: 'static_pages#about'
  get '/started', to: 'static_pages#getting_started'

  # User model, custom routes above resources to match first
  get '/signup', to: 'users#new'
  get '/history/:id', to: 'users#history', as: 'history'
  post '/signup', to: 'users#create'
  resources :users, only: [:show, :edit, :index, :update, :destroy]

  # user account login system
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # markers
  get '/start', to: 'markers#start'
  post '/curriculum', to: 'markers#begin_curriculum'
  get '/theories', to: 'markers#theories'
  get '/resume', to: 'markers#resume_curriculum'
  post '/category/next', to: 'markers#next_category'
  post '/category/skip', to: 'markers#skip_category'
  delete '/start', to: 'markers#reset_curriculum'
  post '/problem/skip', to: 'markers#skip_problem'
  get '/next', to: 'markers#next_unlocked_by_context'

  # answers
  get '/solve/:id', to: 'answers#problem', as: 'solve'
  post '/solve/evaluate', to: 'answers#evaluate'
  post '/solve/:id', to: 'answers#get_hint', as: 'get_hint'

  # problems
  resources :problems, except: [:new, :create]

  # theories
  get '/view/:id', to: 'theories#view', as: 'view'
  get '/theories/index', to: 'theories#index'
  resources :theories, except: [:new, :create, :index]

  # globalgraphs
  resources :globalgraphs, only: [:index, :show]

  # graphs
  resources :graphs, only: [:index, :show]

  # curriculum pages for teachers/admins
  get '/curriculum/edit', to: 'curriculum#index'
  get '/curricula', to: 'curriculum#curricula'
  get '/curriculum/categories', to: 'curriculum#categories'
  get '/curriculum/contexts', to: 'curriculum#contexts'
  get '/curriculum/files', to: 'curriculum#files'
  get '/curriculum/history', to: 'curriculum#history'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-6" id="footerLeft">
        <nav>
          <% if logged_in %>
            <ul>
              <%# TODO unlocked_theories url %>
              <% url = theories_path %>
              <li><%= link_to "Unlocked Theories", url, target: '_blank' %></li>
            </ul>
          <% else %>
            <li><%= link_to "Sign up for free trial!", signup_path %></li>
          <% end %>
        </nav>
      </div>
      <div class="col-xs-6" id="footerRight">
        <nav>
          <ul>
            <li><%= link_to "Support", support_path %></li>
            <li><%= link_to "About",   about_path %></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<%# TODO add dropdown headers, as designed by bootstrap %>
<header class="navbar navbar-fixed-top navbar-inverse">
  <nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2 col-sm-offset-1">
          <div class="navbar-header" id="math_affirm_logo">
            <%= link_to "Math Affirm", root_path, id: "logo" %>
          </div>
        </div>
        <div class="col-sm-4 col-sm-offset-4">
          <ul class="nav navbar-nav navbar-right" id="math_affirm_navbar">
            <%# user account menu %>
            <% if logged_in %>
              <li><%= link_to "Curriculum", start_path %></li>
              <% if is_teacher %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Tools <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li class="dropdown-header">Content</li>
                    <li><%= link_to "Organized Files", curricula_path %></li>
                    <li><%= link_to "Files and Search", curriculum_edit_path %></li>
                    <li class="divider"></li>
                    <li class="dropdown-header">Accounts</li>
                    <li><%= link_to "View Users", users_path %></li>
                    <li class="divider"></li>
                    <li class="dropdown-header">Analytics</li>
                    <li><%= link_to "Users History", curriculum_history_path %></li>
                  </ul>
                </li>
              <% end %>
              <li class="dropdown">
                <%# TODO change to identify user privalege %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= print_user_type %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li class="dropdown-header">Settings</li>
                  <% url = edit_user_path(current_user) %>
                  <li><%= link_to "Account", url %></li>
                  <% url = user_path(current_user) %>
                  <li><%= link_to "Profile", url %></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Activity</li>
                  <% url = history_path(current_user.id) %>
                  <li><%= link_to "History", url %></li>
                  <li class="divider"></li>
                  <%# all users %>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Getting Started", started_path %></li>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <% render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%# error messages shown to client %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    </div>
    <%# page-specific content %>
    <%= yield %>
    <%# Rails.env.development will show in localhost but not heroku %>
    <div class="container">
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>